export interface EnglishWord {
  word: string;
  zh: string;
}

export interface WordUnit {
  id: string;
  label: string;
  words: EnglishWord[];
}

/**
 * 词库依据人教版（2024 版）七年级上册（浙江省/杭州市现行教材）的单元话题整理，
 * 覆盖 Starter Unit 1-3 与 Unit 1-7。每个单元都是该话题下需要掌握的核心词汇，
 * 而不是随意挑选的单词。
 */
export const WORD_BANK_NOTE = "人教版（2024）七年级上册";

export const WORD_UNITS: WordUnit[] = [
  {
    id: "starter-1",
    label: "Starter 1 · Hello!（打招呼）",
    words: [
      { word: "hello", zh: "你好" },
      { word: "hi", zh: "嗨；你好" },
      { word: "good", zh: "好的" },
      { word: "morning", zh: "早晨；上午" },
      { word: "afternoon", zh: "下午" },
      { word: "evening", zh: "傍晚；晚上" },
      { word: "name", zh: "名字" },
      { word: "nice", zh: "令人愉快的；好的" },
      { word: "meet", zh: "遇见；会面" },
      { word: "welcome", zh: "欢迎" },
      { word: "thanks", zh: "谢谢" },
      { word: "fine", zh: "好的；健康的" },
      { word: "teacher", zh: "老师" },
      { word: "student", zh: "学生" },
      { word: "class", zh: "班级" },
      { word: "grade", zh: "年级" },
      { word: "friend", zh: "朋友" },
      { word: "goodbye", zh: "再见" },
    ],
  },
  {
    id: "starter-2",
    label: "Starter 2 · Keep Tidy!（文具与位置）",
    words: [
      { word: "pen", zh: "钢笔" },
      { word: "pencil", zh: "铅笔" },
      { word: "ruler", zh: "尺子" },
      { word: "eraser", zh: "橡皮" },
      { word: "book", zh: "书" },
      { word: "dictionary", zh: "词典" },
      { word: "schoolbag", zh: "书包" },
      { word: "pencil box", zh: "铅笔盒" },
      { word: "desk", zh: "书桌" },
      { word: "chair", zh: "椅子" },
      { word: "room", zh: "房间" },
      { word: "tidy", zh: "整洁的" },
      { word: "in", zh: "在……里面" },
      { word: "on", zh: "在……上面" },
      { word: "under", zh: "在……下面" },
      { word: "where", zh: "在哪里" },
      { word: "find", zh: "找到" },
      { word: "lost", zh: "丢失的" },
    ],
  },
  {
    id: "starter-3",
    label: "Starter 3 · Welcome!（课堂用语）",
    words: [
      { word: "classmate", zh: "同学" },
      { word: "sit", zh: "坐" },
      { word: "stand", zh: "站" },
      { word: "open", zh: "打开" },
      { word: "close", zh: "关上" },
      { word: "listen", zh: "听" },
      { word: "look", zh: "看" },
      { word: "read", zh: "读" },
      { word: "write", zh: "写" },
      { word: "please", zh: "请" },
      { word: "sorry", zh: "对不起" },
      { word: "again", zh: "再一次" },
      { word: "spell", zh: "拼写" },
      { word: "answer", zh: "回答；答案" },
      { word: "question", zh: "问题" },
      { word: "understand", zh: "理解" },
      { word: "repeat", zh: "重复" },
      { word: "help", zh: "帮助" },
    ],
  },
  {
    id: "unit-1",
    label: "Unit 1 · You and Me（自我介绍）",
    words: [
      { word: "name", zh: "名字" },
      { word: "first name", zh: "名字" },
      { word: "last name", zh: "姓" },
      { word: "age", zh: "年龄" },
      { word: "old", zh: "……岁的；老的" },
      { word: "year", zh: "年" },
      { word: "from", zh: "来自" },
      { word: "China", zh: "中国" },
      { word: "England", zh: "英格兰" },
      { word: "English", zh: "英语；英国的" },
      { word: "city", zh: "城市" },
      { word: "live", zh: "居住" },
      { word: "class", zh: "班级" },
      { word: "grade", zh: "年级" },
      { word: "middle school", zh: "中学" },
      { word: "phone", zh: "电话" },
      { word: "number", zh: "号码" },
      { word: "email", zh: "电子邮件" },
      { word: "know", zh: "认识；知道" },
      { word: "friend", zh: "朋友" },
    ],
  },
  {
    id: "unit-2",
    label: "Unit 2 · We're Family!（家庭）",
    words: [
      { word: "family", zh: "家庭" },
      { word: "parent", zh: "父亲；母亲" },
      { word: "mother", zh: "母亲" },
      { word: "father", zh: "父亲" },
      { word: "brother", zh: "兄弟" },
      { word: "sister", zh: "姐妹" },
      { word: "grandfather", zh: "祖父；外祖父" },
      { word: "grandmother", zh: "祖母；外祖母" },
      { word: "aunt", zh: "姑母；姨母" },
      { word: "uncle", zh: "叔叔；舅舅" },
      { word: "cousin", zh: "堂/表兄弟姐妹" },
      { word: "son", zh: "儿子" },
      { word: "daughter", zh: "女儿" },
      { word: "photo", zh: "照片" },
      { word: "love", zh: "爱" },
      { word: "home", zh: "家" },
      { word: "family tree", zh: "家谱" },
      { word: "only child", zh: "独生子女" },
      { word: "look like", zh: "看起来像" },
      { word: "together", zh: "一起" },
    ],
  },
  {
    id: "unit-3",
    label: "Unit 3 · My School（校园与方位）",
    words: [
      { word: "school", zh: "学校" },
      { word: "classroom", zh: "教室" },
      { word: "library", zh: "图书馆" },
      { word: "playground", zh: "操场" },
      { word: "dining hall", zh: "餐厅" },
      { word: "art room", zh: "美术教室" },
      { word: "music room", zh: "音乐教室" },
      { word: "computer room", zh: "计算机教室" },
      { word: "science lab", zh: "科学实验室" },
      { word: "teachers' office", zh: "教师办公室" },
      { word: "building", zh: "建筑物；楼" },
      { word: "floor", zh: "楼层" },
      { word: "hall", zh: "大厅" },
      { word: "next to", zh: "在……旁边" },
      { word: "behind", zh: "在……后面" },
      { word: "in front of", zh: "在……前面" },
      { word: "between", zh: "在……之间" },
      { word: "near", zh: "在……附近" },
      { word: "clean", zh: "干净的" },
      { word: "beautiful", zh: "美丽的" },
      { word: "big", zh: "大的" },
      { word: "small", zh: "小的" },
    ],
  },
  {
    id: "unit-4",
    label: "Unit 4 · My Favourite Subject（学科）",
    words: [
      { word: "subject", zh: "学科" },
      { word: "Chinese", zh: "语文；中文" },
      { word: "maths", zh: "数学" },
      { word: "English", zh: "英语" },
      { word: "science", zh: "科学" },
      { word: "history", zh: "历史" },
      { word: "geography", zh: "地理" },
      { word: "art", zh: "美术" },
      { word: "music", zh: "音乐" },
      { word: "PE", zh: "体育" },
      { word: "IT", zh: "信息技术" },
      { word: "favourite", zh: "最喜欢的" },
      { word: "because", zh: "因为" },
      { word: "interesting", zh: "有趣的" },
      { word: "fun", zh: "有趣的；乐趣" },
      { word: "easy", zh: "容易的" },
      { word: "difficult", zh: "困难的" },
      { word: "useful", zh: "有用的" },
      { word: "important", zh: "重要的" },
      { word: "timetable", zh: "课程表" },
      { word: "lesson", zh: "课" },
      { word: "Monday", zh: "星期一" },
      { word: "Tuesday", zh: "星期二" },
      { word: "Wednesday", zh: "星期三" },
      { word: "Thursday", zh: "星期四" },
      { word: "Friday", zh: "星期五" },
    ],
  },
  {
    id: "unit-5",
    label: "Unit 5 · Fun Clubs（社团与技能）",
    words: [
      { word: "club", zh: "俱乐部；社团" },
      { word: "join", zh: "加入" },
      { word: "sing", zh: "唱歌" },
      { word: "dance", zh: "跳舞" },
      { word: "draw", zh: "画画" },
      { word: "paint", zh: "绘画；涂色" },
      { word: "swim", zh: "游泳" },
      { word: "run", zh: "跑" },
      { word: "jump", zh: "跳" },
      { word: "play", zh: "玩；打（球）" },
      { word: "basketball", zh: "篮球" },
      { word: "football", zh: "足球" },
      { word: "ping-pong", zh: "乒乓球" },
      { word: "chess", zh: "国际象棋" },
      { word: "guitar", zh: "吉他" },
      { word: "piano", zh: "钢琴" },
      { word: "violin", zh: "小提琴" },
      { word: "drum", zh: "鼓" },
      { word: "speak", zh: "说（某种语言）" },
      { word: "tell stories", zh: "讲故事" },
      { word: "can", zh: "能；会" },
      { word: "well", zh: "好地" },
    ],
  },
  {
    id: "unit-6",
    label: "Unit 6 · A Day in the Life（作息时间）",
    words: [
      { word: "get up", zh: "起床" },
      { word: "go to bed", zh: "上床睡觉" },
      { word: "do homework", zh: "做作业" },
      { word: "have breakfast", zh: "吃早餐" },
      { word: "have lunch", zh: "吃午餐" },
      { word: "have dinner", zh: "吃晚餐" },
      { word: "brush teeth", zh: "刷牙" },
      { word: "wash face", zh: "洗脸" },
      { word: "take a shower", zh: "洗澡" },
      { word: "go to school", zh: "去上学" },
      { word: "go home", zh: "回家" },
      { word: "exercise", zh: "锻炼" },
      { word: "o'clock", zh: "……点钟" },
      { word: "half past", zh: "半点" },
      { word: "night", zh: "夜晚" },
      { word: "usually", zh: "通常" },
      { word: "always", zh: "总是" },
      { word: "often", zh: "经常" },
      { word: "sometimes", zh: "有时" },
      { word: "never", zh: "从不" },
      { word: "early", zh: "早的；早地" },
      { word: "late", zh: "迟的；晚地" },
    ],
  },
  {
    id: "unit-7",
    label: "Unit 7 · Happy Birthday!（日期与庆祝）",
    words: [
      { word: "birthday", zh: "生日" },
      { word: "date", zh: "日期" },
      { word: "month", zh: "月份" },
      { word: "January", zh: "一月" },
      { word: "February", zh: "二月" },
      { word: "March", zh: "三月" },
      { word: "April", zh: "四月" },
      { word: "May", zh: "五月" },
      { word: "June", zh: "六月" },
      { word: "July", zh: "七月" },
      { word: "August", zh: "八月" },
      { word: "September", zh: "九月" },
      { word: "October", zh: "十月" },
      { word: "November", zh: "十一月" },
      { word: "December", zh: "十二月" },
      { word: "cake", zh: "蛋糕" },
      { word: "party", zh: "聚会" },
      { word: "present", zh: "礼物" },
      { word: "gift", zh: "礼物" },
      { word: "card", zh: "贺卡" },
      { word: "balloon", zh: "气球" },
      { word: "candle", zh: "蜡烛" },
      { word: "wish", zh: "祝愿" },
      { word: "invite", zh: "邀请" },
    ],
  },
];

export function getUnit(id: string): WordUnit {
  return WORD_UNITS.find((unit) => unit.id === id) ?? WORD_UNITS[0];
}

export function totalWordCount(): number {
  return WORD_UNITS.reduce((sum, unit) => sum + unit.words.length, 0);
}

export function shuffle<T>(items: readonly T[]): T[] {
  const result = [...items];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}
